version: '3.8'
services:
  app:
    build: .
    container_name: configurable-test-suite
    ports:
      - "4001:4001"
    environment:
      - ENV=dev
      - HEADLESS=true
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=testreports
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    container_name: cts-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
